### ISSUE TITLE
Compressing Image

### ISSUE THREAD

**Issue by Sparkenstein** [silvia-odwyer/photon#137]
I searched through the issued but I couldn't find a way to just `compress` the image. 
I want to convert an image from any type (jpeg/png/webp) etc to any other, while compressing the size, keeping original dimensions
Can you point me to a direction

**Comment by silvia-odwyer** [comment]
@Sparkenstein Thanks for opening this issue! 😄 Unfortunately this functionality is not yet available, but that being said,  there is a `get_bytes_jpeg` function (view [here](https://github.com/silvia-odwyer/photon/blob/d3853981d987151b4c1971f1e8e6ed27e0eed98e/crate/src/lib.rs#L154)), with a `quality` parameter that you can specify in order to change the image quality. However I do agree that a `compress` function should also be included as part of the library. 👍

**Comment by Sparkenstein** [comment]
Hey thanks for the explanation.  I believe the function `get_bytes_jpeg` should work for me, but it looks like it's only for jpegs. I am currently working on a tool that can not only compress but as well change format. like [squoosh](https://squoosh.app/). 
Maybe I can have a workaround for now like writing the alternative function myself?  I believe I only need to replace `image::ImageOutputFormat::Jpeg` with my required formats. 
Do you have any plans to add this feature in the lib itself in upcoming days?

**Comment by silvia-odwyer** [comment]
We now have a general method for compressing JPEG images, thanks to #139 🎉 
The next part to work on is adding support for multiple image formats also ✅

**Comment by an1217** [comment]
I use compress to specify the quality of 3, but its quality is reduced from 4.37 to 4.12, and when I specify 30, it becomes 5. What's wrong with this and he's using time 148s
