### ISSUE TITLE
cargo run --release  got Err

### ISSUE THREAD

**Issue by goodforever** [silvia-odwyer/photon#14]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5

**Comment by silvia-odwyer** [comment]
Hi @goodforever! Thanks for opening this issue! 
You'll need to provide an image in the directory that matches the file specified in `bin.rs`. There are two sample images provided in the `examples/input_examples` directory, if you rename one of the images to the filename specified in bin.rs, that should do the trick. Or else, you can modify bin.rs so that the image `daisy_fuji.jpg` will be filtered instead. You'll find bin.rs in the `crate/src/bin` directory, navigate to line 6 and modify the file path by changing `test_image.png` to `daisy_fuji.jpg`.

So line 6 should now be:
```rs
let mut img = open_image("examples/input_images/daisy_fuji.jpg");
```
Now that photon can find that image in the file path specified, and since the image exists, you shouldn't get any errors.
I will update the bin in the next release so that this won't occur for future developers running the code. Thanks again!

**Comment by goodforever** [comment]
Thanks! successfully
