### ISSUE TITLE
Question: is there dec_brightness similar to inc_brightness?

### ISSUE THREAD

**Issue by dallasgere** [silvia-odwyer/photon#190]
Hello, I wanted to ask about some of the functions available in photon. I noticed that in the effects there is the inc_brightness function but there is not a dec_brightness one as well. 

I have also noticed in colour_spaces there is the darken/lighten functions for hsl, hsv, lch, hsluv. Could the functionality from a dec_brightness function be achieved through the colour_spaces darken functions? Or are those going to give different results?

I am new to image processing so I am trying to learn/let me know if I have over looked anything.

Thanks!

**Comment by silvia-odwyer** [comment]
@dallasgere Thanks for opening this issue. You can pass a negative number to the inc_brightness function, and it will reduce the brightness. However, I see that the name may be confusing, so I will update it to be `adj_brightness` instead.

**Comment by silvia-odwyer** [comment]
@dallasgere I've changed the name of the function to `adjust_brightness` instead, and if you pass a negative number to this function, the brightness will be reduced. I've also added a new `dec_brightness` function too, and if you pass a u8 number to this, the brightness will be reduced by that constant. Since it has been implemented, I will now close this issue ✅
