### ISSUE TITLE
Feature request: panic-free functions

### ISSUE THREAD

**Issue by gengteng** [silvia-odwyer/photon#28]
I think it would be better to reimplement `open_image` and `save_image` as  panic-free functions that return `Result<T, E>`. for example:

```
impl PhotonImage {
    pub fn open<P: AsRef<Path>>(path: P) -> Result<Self, PhotonError> {
        // open image ...
    }

    pub fn save_as<P: AsRef<Path>>(&self, path: P) -> Result<(), PhotonError> {
        // save image ...
    }
}
```

`bin.rs` :

```
fn main() -> Result<(), PhotonError>  {
    // Open the image (a PhotonImage is returned)
    let mut img = PhotonImage::open("examples/input_images/daisies_fuji.jpg")?;

    // Increment the red channel by 40
    photon_rs::channels::alter_red_channel(&mut img, 40);

    let output_img_path = "raw_image.jpg";

    // Write file to filesystem.
    img.save_as(output_img_path)?;    

    println!("Saved image: {}. Please check this directory for the image.", output_img_path);

    Ok(())
}
```

**Comment by silvia-odwyer** [comment]
Hi @gengteng, thanks for the suggestion! I'm hoping to include this feature in version 0.3.0 of the library (currently it's at 0.2.0), so that's definitely in the plans 😄

**Comment by elpiel** [comment]
I want to work on this. Couple of questions:

1. Which functions / methods do you think should be panic-free?
2. How should we separate the different errors ( if we need to implement errors other functions/methods )?
3. Could we add a dependency like `thiserror` for easy implementation of the errors?

**Comment by silvia-odwyer** [comment]
Hi @elpiel I'm delighted that you want to work on this, much appreciated! 😄 

I think it would be great if both the `open_image` and `save_image` functions are panic-free. Those are the main two I'd like to put priority on. 

As for separating the different errors, one error could be an ImageNotFound for the open_image function if the image doesn't exist, and another OutputError if the image can't be written to the filesystem. Feel free to change the names as you see fit, but that's the general idea of what I'd like to achieve.

Definitely, using a dependency such as `thiserror` would make things easier, so feel free to make use of it! Thanks again 👍

**Comment by elpiel** [comment]
Hey @silvia-odwyer , no worries, happy to help! The library looks interesting and I thought I would take a stab on couple of features.

**Comment by osman-turan** [comment]
@silvia-odwyer What's the status of this issue? From commit history, I see it was implemented and then reversed for save functions due to some reason.

Also, if it will be implemented for save functions, I don't think it's a good idea to use 2 different error structs/enums for open and save functions separately. Because, when someone tries to use error propagating within the same function for open and save operations, it will get verbose quickly. I suggest using the same error enum for both functions.

If you are fine with my points, I can push a PR to cover them. We can discuss further about them at the PR if you like.

**Comment by silvia-odwyer** [comment]
@osman-turan That's a good point about not using 2 different error structs/enums for both save and open functions separately. Using one error enum for both would be perfect 👍 Sure, if you're interested in working on this, that would be fantastic! 😄

**Comment by osman-turan** [comment]
[This](https://github.com/silvia-odwyer/photon/pull/113) should solve this issue with the exception of `ImageBuffer::from_vec` originated panic. As I noted in the PR, I believe it should panic for this method. Because it indicates an invocation issue of the function itself - not related to user inputs.

**Comment by silvia-odwyer** [comment]
@osman-turan Perfect, thanks for the PR! I've just merged it, and this seems to be fixed now, so I'll close this issue ✅ Thanks again!
