### ISSUE TITLE
What is the name of the npm package?

### ISSUE THREAD

**Issue by RobertWHurst** [silvia-odwyer/photon#5]
Firstly, this is a fantastic library, thank you for sharing it with the community.

I'm trying to use it in a node project, but I can't seem to find the documentation for usage with JS in node. Is there a npm package I can install, or do I need to write my own bindings to the lib?

**Comment by silvia-odwyer** [comment]
Hi Robert, 
I'm delighted you've decided to use Photon with a Node project; that's pretty exciting! The first release of Photon as an npm package will be in the coming weeks, so it will be installable via npm pretty soon.

However, until then, you can generate the npm package directly and then use it as per usual in your node project (by using npm link, if you need more info on that, just let me know).

You'll need the wasm-pack build tool. You can get it here: https://rustwasm.github.io/wasm-pack/

Then, once you have installed wasm-pack, move into the `crate` sub-directory and run the following command:

`wasm-pack build`

This will compile the crate to WebAssembly and output a `./pkg` (equivalent to an npm module). You'll find this in the crate directory, and can then move it into your node project's node modules, then just use npm's link functionality to link the module.

Hopefully this helps, and let me know if you have any other questions, I'll be more than happy to help.

**Comment by sheerun** [comment]
Can't wait for npm package :)

**Comment by silvia-odwyer** [comment]
@RobertWHurst @sheerun The npm package is available here: https://www.npmjs.com/package/@silvia-odwyer/photon

@RobertWHurst If you're intending to use Photon with NodeJS, I'd recommend you use this package instead, which is tailored to NodeJS (this ensures it can be imported via `require`): https://www.npmjs.com/package/@silvia-odwyer/photon-node

I've been testing it for the last few days, to ensure that all works as expected, which is why I slightly delayed announcing it here. 

If you have any questions relating to usage, be sure to let me know! Thanks again! 😄

**Comment by sheerun** [comment]
Do you know how to use it with create-react-app? I get following error:

```
./node_modules/@silvia-odwyer/photon/photon.js
Module not found: Can't resolve './photon_bg' in '/Users/sheerun/Source/Experiment/rubik/node_modules/@silvia-odwyer/photon'
```

**Comment by sheerun** [comment]
Also If I manually change `import * as wasm from './photon_bg';` to `import * as wasm from './photon_bg.wasm';` then I get another error:

```
Failed to compile.

./node_modules/@silvia-odwyer/photon/photon_bg.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
 * ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
```

**Comment by silvia-odwyer** [comment]
You'll need a WASM loader, so if you install wasm-loader (`npm install --save wasm-loader`) and add the following to create react app's `config-overrides.js`, within the `override` function, it should fix that issue for you:

```js
  const wasmExtensionRegExp = /\.wasm$/;

  config.resolve.extensions.push('.wasm');

  config.module.rules.forEach(rule => {
    (rule.oneOf || []).forEach(oneOf => {
      if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
        // Make file-loader ignore WASM files
        oneOf.exclude.push(wasmExtensionRegExp);
      }
    });
  });

  // Add a dedicated loader for WASM
  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, 'src'),
    use: [{ loader: require.resolve('wasm-loader'), options: {} }]
  });
```
You can see a complete example of this here: https://github.com/silvia-odwyer/photon/blob/master/react_app_demo/config-overrides.js

I'll add a note on this in the documentation so it helps others in the future. 
If there are other issues, do let me know! Hope this helps 😄

**Comment by sheerun** [comment]
@silvia-odwyer It works very well. The only nitpick is that source you export uses no `.wasm` extension for was import which makes `config.resolve.extensions.push('.wasm');` necessary and is not compatible with upcoming node ES6 imports which require explicit extensions.

It's very weird because the source I'm exporting with `wasm-pack build` is very different than yours. Are you using newest version? Here's screenshot comparing two:

https://imgur.com/a/JwrK9QW

**Comment by silvia-odwyer** [comment]
@sheerun Thanks for flagging this issue, I had a look into what was causing the different outputs, and it appears I wasn't using an up-to-date version of wasm-pack. I'm going to watch out for this in future.

Also, I'm going to update the npm modules, so that the source of each version will include a file with the `.wasm` extension. Thanks so much for pointing this out, Adam!

**Comment by sheerun** [comment]
I've submitted WASM support out of the box to create-react-app but I would not count it'll be merged soon given state of their issues and PRs: https://github.com/facebook/create-react-app/pull/8303

**Comment by jhodges10** [comment]
@silvia-odwyer probably good to close this issue now?

**Comment by silvia-odwyer** [comment]
Sounds good, just a final note for those from the future who read this:

Photon's npm package is found here, for the browser/web: https://www.npmjs.com/package/@silvia-odwyer/photon

Photon Node's npm package is found here, for Node.js applications: https://www.npmjs.com/package/@silvia-odwyer/photon-node
