### ISSUE TITLE
[Bug]: photon-rs v0.3.0 doesn't contain padding functionality under src/transform.rs

### ISSUE THREAD

**Issue by gp-97** [silvia-odwyer/photon#84]
The Github repo has it, but the crate at crates.io doesn't have the padding feature. Please look into it. TIA.

**Comment by silvia-odwyer** [comment]
Hi @gp-97 I've looked into it, and I've seen the issue. The code was included as part of v0.3.0, but since the wasm_bindgen annotations weren't added to the functions, they weren't exposed, so you couldn't call them. 

But I've just added the annotations, and created a new Rgba struct which replaces the tuple parameters that represented the padding color. This is to make the code WebAssembly-friendly, since the IntoWasmAbi trait isn't implemented for those currently (you can see this [here](https://github.com/silvia-odwyer/photon/commit/e31b7b3228fdb6c3143ab870fdb6539ea34dd2c7)). If you have any other requests for changes before this is released, do let me know 👍 

Thanks so much for letting me know about this, much appreciated! 😄

**Comment by gp-97** [comment]
Oh nice. Thanks @silvia-odwyer for fixing this issue.

**Comment by gp-97** [comment]
@silvia-odwyer. Correct me if I am wrong, but I think the github repo has been updated, but the crate hasn't been, because the problem still persists.

**Comment by silvia-odwyer** [comment]
Hi @gp-97 I'm planning on releasing the new version of the library this Tuesday, and it will contain the new frosted glass effect also! 😄 So I'll leave this issue open until it gets released 👍

**Comment by silvia-odwyer** [comment]
@gp-97 I just released version 0.3.1, which includes your latest contributions, thanks again!  The Rgba struct should be available now also 🎉
