### ISSUE TITLE
[Question] Would this library be useful for chroma keying?

### ISSUE THREAD

**Issue by AdamJaggard** [silvia-odwyer/photon#96]
I'm researching libraries for real-time chroma keying (green screening effect) in the browser (canvas based). Do you think Photon would be a good choice for such a task? I have a working prototype using web workers in vanilla JS which runs OK but just looking for higher performance options. I saw you had HSV functions which is how we're defining the key but unsure how to use the library to turn specific pixels transparent that fit within a H-S-V threshold. Any point in the right direction appreciated.

**Comment by silvia-odwyer** [comment]
Hi Adam! 
I'd recommend WebGL for this, due to the real-time aspect of the project. While Photon could also be used, I would expect much greater performance from WebGL overall.
This library could be what you're looking for: https://github.com/brianchirls/Seriously.js 
It supports chroma keying, and works in-browser too! Hopefully that helps out, and make sure to let me know if you have any other questions! 😄

**Comment by AdamJaggard** [comment]
Thanks Silvia, I guessed real-time rendering wasn't a goal of Photon. I'm going to keep it bookmarked for future use cases though as it looks very useful. We currently have a 2d canvas stack doing various things so won't be able to utilise webgl in the short term but something to consider for the future for sure, thanks for the suggestion.
